apiVersion: apps/v1
kind: Deployment
metadata:
  name: decksecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdso
  template:
    metadata:
      labels:
        app: appdso
    spec:
      containers:
      - name: decksecops
        image: chrimson/decksecops:latest
        ports:
        - containerPort: 5000

