apiVersion: apps/v1
kind: Deployment
metadata:
  name: decksecops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appdso
  template:
    metadata:
      labels:
        app: appdso
    spec:
      containers:
      - name: decksecops
        image: chrimson/decksecops:latest
        ports:
        - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appweb
  template:
    metadata:
      labels:
        app: appweb
    spec:
      containers:
      - name: aspnet
        image: chrimson/webapp:latest
        ports:
        - containerPort: 5091
