apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: set
spec:
  serviceName: svc
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: web
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: storage
          mountPath: /usr/share/nginx
      - name: db
        image: chrimson/sqlite3:latest
        command: ["/bin/sh", "-c", "tail -f /dev/null"]
        volumeMounts:
        - name: storage
          mountPath: /opt
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: pvc
