apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sqlnginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: appsqlngx
  template:
    metadata:
      labels:
        app: appsqlngx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: storage
          mountPath: /usr/share/nginx
        - name: share
          mountPath: /tmp
      - name: sql
        image: chrimson/sqlite3:latest
        command: ["/bin/sh", "-c", "tail -f /dev/null"]
        volumeMounts:
        - name: storage
          mountPath: /opt
        - name: share
          mountPath: /tmp
      volumes:
      - name: storage
        persistentVolumeClaim:
          claimName: pvc
      - name: share
        emptyDir: {}
