apiVersion: v1
kind: Service
metadata:
  name: decksecops
spec:
  type: NodePort
  selector:
    app: appdso
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  type: NodePort
  selector:
    app: appweb
  ports:
  - protocol: TCP 
    port: 5091
    targetPort: 5091
